"""
FocusMate - Dashboard Module
STEP 3: Organize into tabs matching the 3-stage demo structure

Goal of this stage:
    Same content as Step 2, but reorganized into three tabs that map
    directly onto the competition's required structure:
        Tab 1 = Introduce the Problem
        Tab 2 = Core Interactive Challenge (live stats + manual habits)
        Tab 3 = Reflection / Result (session summary + tips)

    Still placeholder/dummy data - only the STRUCTURE changes in this step.

Run with (PowerShell):
    streamlit run step3_tabs.py
"""

import streamlit as st

st.set_page_config(
    page_title="FocusMate",
    page_icon="🧠",
    layout="wide",
)

st.title("🧠 FocusMate")
st.caption("An AI wellbeing dashboard for better study posture and screen habits.")

# ---------------------------------------------------------------------------
# Create the three tabs. Streamlit returns one "container" per tab - we
# write content into each using "with tab_name:"
# ---------------------------------------------------------------------------
tab1, tab2, tab3 = st.tabs(
    ["1️⃣ Introduce the Problem", "2️⃣ Live Challenge", "3️⃣ Reflection & Results"]
)

# ---------------------------------------------------------------------------
# TAB 1: Introduce the Problem
# ---------------------------------------------------------------------------
with tab1:
    st.header("The Problem")
    st.write(
        "After 30 minutes of studying, do you actually know how your "
        "posture changed? How many times you leaned in too close to the "
        "screen? How long you looked away, distracted?"
    )
    st.write(
        "Most students have no idea - these habits build up silently "
        "during a study session, and by the time you notice discomfort "
        "or tiredness, it's already been happening for a while."
    )
    st.write(
        "**FocusMate watches these signals during your study session and "
        "shows you what's really happening - then gives you simple, "
        "personalized tips to fix it.**"
    )

    if st.button("Start Session ▶️", type="primary"):
        st.info("This button will eventually start the live webcam session. Coming in a later step.")

# ---------------------------------------------------------------------------
# TAB 2: Core Interactive Challenge (live stats + manual habit logging)
# ---------------------------------------------------------------------------
with tab2:
    st.header("📊 Live Session Stats")
    st.caption(
        "Placeholder values for now - will update in real time once "
        "connected to the webcam detection module."
    )

    col1, col2, col3, col4 = st.columns(4)
    placeholder_focus_score = 82
    placeholder_posture_alerts = 4
    placeholder_looking_away = 2
    placeholder_session_minutes = 18

    col1.metric("Focus Score", f"{placeholder_focus_score}/100")
    col2.metric("Posture Alerts", placeholder_posture_alerts)
    col3.metric("Looking Away Events", placeholder_looking_away)
    col4.metric("Session Time", f"{placeholder_session_minutes} min")

    st.divider()

    st.header("💧 Manual Habit Logging")
    st.caption("Log habits by hand that the webcam can't detect on its own.")

    habit_col1, habit_col2, habit_col3 = st.columns(3)

    with habit_col1:
        water_glasses = st.number_input(
            "Glasses of water today", min_value=0, max_value=20, value=0, step=1
        )
    with habit_col2:
        breaks_taken = st.number_input(
            "Breaks taken this session", min_value=0, max_value=20, value=0, step=1
        )
    with habit_col3:
        sleep_hours = st.slider(
            "Hours of sleep last night", min_value=0.0, max_value=12.0, value=7.0, step=0.5
        )

    st.write(
        f"Logged so far: **{water_glasses} glasses of water**, "
        f"**{breaks_taken} breaks**, **{sleep_hours} hours of sleep**."
    )

# ---------------------------------------------------------------------------
# TAB 3: Reflection / Result
# ---------------------------------------------------------------------------
with tab3:
    st.header("📝 Session Summary")
    st.caption("This is shown at the end of a study session.")

    st.info(
        "Example placeholder summary:\n\n"
        "Your 25-minute session\n"
        "- Posture alerts: 7\n"
        "- Long distractions: 3\n"
        "- Breaks taken: 1\n"
        "- Focus score: 78%\n\n"
        "*(This will be generated automatically from real session data later.)*"
    )

    st.subheader("💡 FocusMate Feedback")
    st.success(
        "Example tip: \"You had several posture alerts during the final "
        "10 minutes. Try raising your screen and taking a short movement "
        "break before your next session.\"\n\n"
        "*(Real tips will be generated by rule-based logic in a later step.)*"
    )
